### ISSUE TITLE
Update does not work correctly with reused branches

### ISSUE THREAD

**Issue by zweigraf** [yonaskolb/Mint#12]
In my project I reused a branch name (`mint`, for development).

So the local mint checkout folder already contained a `mint` branch from an earlier checkout and now origin contains a new `mint` branch, which is basically completely different from the local `mint` branch.

When running `git checkout <branch name>` in <https://github.com/yonaskolb/Mint/blob/master/Sources/MintKit/MintKit.swift#L124> through `$ mint update gnosis/bivrost-swift@mint` Mint just checkouts the local branch again, ignoring the new branch on origin, building the old version again. So basically using `update` forces it to rebuild, but not to actually update the version it builds.

Solutions:
- In my simple tests, just adding `origin/` to the branch name could work (not sure about tagged versions though). So the command then would be `git checkout origin/mint`, which checks out the latest origin branch.
- You could also clear the checkouts folder before fetching, which would have the same effect.

In addition, `update` fails [here](https://github.com/yonaskolb/Mint/blob/master/Sources/MintKit/MintKit.swift#L133) when the repo name is not the same as the command name, which might have a technical reason, but is counter intuitive because I only want to update the package, not actually run it.

Maybe adding a `Mintfile` could help with this, as it could identify how the executable is named. Or Mint could just copy all executables that are produced by SPM.

**Comment by yonaskolb** [comment]
Hi @zweigraf, thanks for posting the issue.
Yes, I see the problem. We should checkout the remote branch, which should fix that. If you had time to make a PR that would be great. Otherwise I’ll have a look at this next week.

In terms of the repo name and executable name mismatch, you would have to specify the executable name on install as well. This won’t actually execute the tool, but just helps mint find what to install. I guess we could parse the Package.swift file and if it has any executable products and use that. Not every package defines those products though, so this would just be a fallback solution

**Comment by zweigraf** [comment]
For the first issue: I am not planning on opening a PR yet, but maybe manually cleaning the checkouts folder annoys me enough at one point to still do it 😄 

I see about the second issue. I was under the impression that Mint could maybe just copy everything in the SPM build folder that is marked executable, but there is a lot more in there, which I guess doesn't make sense.

**Comment by SDGGiesbrecht** [comment]
Subset of #18.

**Comment by SDGGiesbrecht** [comment]
For the executable name issue, let’s move the conversation to a distinct issue: #17.
